"""initial setup

Revision ID: 3bf79e960a45
Revises: 
Create Date: 2025-04-09 08:53:26.991729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf79e960a45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('Undefined', 'Scholar', 'Manager', name='roleenum'), nullable=True),
    sa.Column('discord_reference', sa.String(), nullable=True),
    sa.Column('discord_enabled', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('account')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
