"""Add alt_accounts, scholar_accounts, available_for_hire to users

Revision ID: 756b8d21f7a8
Revises: 20ea8822a1b7
Create Date: 2025-06-19 19:20:37.422170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756b8d21f7a8'
down_revision: Union[str, None] = '20ea8822a1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column nullable with no default
    op.add_column('users', sa.Column('alt_accounts', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('scholar_accounts', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('available_for_hire', sa.Boolean(), nullable=True))

    # Step 2: Fill column values in bulk
    op.execute("UPDATE users SET alt_accounts = '[]'")
    op.execute("UPDATE users SET scholar_accounts = '[]'")
    op.execute("UPDATE users SET available_for_hire = true")

    # Step 3: Alter to NOT NULL
    op.alter_column('users', 'alt_accounts', nullable=False)
    op.alter_column('users', 'scholar_accounts', nullable=False)
    op.alter_column('users', 'available_for_hire', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'available_for_hire')
    op.drop_column('users', 'scholar_accounts')
    op.drop_column('users', 'alt_accounts')
    # ### end Alembic commands ###
