[scholar]
primaryColor="#bc6c25"
backgroundColor="#fefae0"
secondaryBackgroundColor="#dda15e"
textColor="#283618"
rowAColor="#dda15e"
rowBColor="#bc6c25"
font="serif"

[dark]
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
rowAColor="#111"
rowBColor="#222"
font="sans serif"

[light]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
rowAColor="#edede9"
rowBColor="#d5bdaf"
font="sans serif"
